[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"

[[edge_functions]]
  path = "/api/get-greeting"
  function = "hello"

[[edge_functions]]
  path = "/uses/"
  function = "geo-amazon"

[[edge_functions]]
  path = "/uses"
  function = "geo-amazon"
