[build]
  command = "npm run breadbox && npm run build"
  publish = "public"
  functions = "functions"

[dev]
  command = "npm run build && npm run serve"
  targetPort = 5000
  framework = "#custom"

[[plugins]]
  package = "netlify-plugin-inline-source"

[[plugins]]
  package = "netlify-plugin-deploy-preview-commenting"
